# Generated by Django 5.2 on 2025-04-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=300)),
                ('published_date', models.DateField()),
                ('genre', models.CharField(choices=[('love', 'Love'), ('thriller', 'Thriller'), ('horror', 'Horror'), ('romance', 'Romance'), ('sci-fi', 'Sci-Fi'), ('mystry', 'Mystry'), ('comedy', 'Comedy')], max_length=100)),
            ],
        ),
    ]
