# Generated by Django 5.2 on 2025-04-20 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_book_genre_alter_book_title_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_at', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('returned', 'Returned'), ('borrowed', 'Borrowed')], default='borrowed', max_length=50)),
                ('borrowed_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.book')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
