# Generated by Django 5.2 on 2025-04-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_borrowingrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowingrecord',
            name='return_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
