# Generated by Django 5.2 on 2025-04-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_borrowingrecord_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowingrecord',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
